title: "MLKN.lab"
description: "MultiLayer Knowledge Network — Ideas Laboratory"
author: "François Papin"
baseurl: ""
url: "https://francoispapin.github.io"
exclude:
  - "*.py"
  - "node_modules/"
  - ".git/"
  - "*.zip"
